"""Advisory-tracker launch-audit corpus (Plan 207 Ph1, D-P207-1).

GENERATED by scripts/gen_advisory_corpus.py -- do not hand-edit; re-run the
generator against a newer tracker export instead. Mapping rules + exclusion
policy are documented in the generator (D-P207-2/3/4); field semantics are
authoritative in the v3 SIMULATION_MODEL.md.

Source workbook: Advisory - Financial Planning Tracker (3).xlsx
Clients: 25; goals: 58; excluded rows: 8.
"""

import pandas as pd

# Pinned for determinism (all tracker goal dates are >= 2027).
TODAY = pd.Timestamp("2026-06-01")

ADVISORY_CLIENTS = {
    'Aditya & Shivika Agarwal (123_M3)': [
        {'name': "Daughter's education", 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2041-03-01', 'amount': 2500000.0, 'inflation_percent': 10.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 4},
        {'name': "Son's Education", 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2043-03-01', 'amount': 2500000.0, 'inflation_percent': 10.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 4},
    ],
    'Ajith Hegde / Amritha Hegde (129_M3)': [
        {'name': 'Financial Freedom', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2034-02-01', 'amount': 200000.0, 'inflation_percent': 6.0, 'frequency': 'Monthly', 'end_mode': 'Occurrences', 'occurrences': 480},
    ],
    'Anjan Yerubandi (110_M3)': [
        {'name': 'Home Purchase', 'type': 'Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2031-01-01', 'amount': 30000000.0, 'inflation_percent': 6.0},
    ],
    'Ayush Khandelwal (159_M3)': [
        {'name': 'Child UG', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2039-01-01', 'amount': 500000.0, 'inflation_percent': 8.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 3},
        {'name': 'Child PG', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2043-01-01', 'amount': 500000.0, 'inflation_percent': 8.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 3},
        {'name': "Child's Wedding", 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2046-01-01', 'amount': 5000000.0, 'inflation_percent': 6.0},
        {'name': 'Retirement Income', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2043-01-01', 'amount': 80000.0, 'inflation_percent': 6.0, 'frequency': 'Monthly', 'end_mode': 'Occurrences', 'occurrences': 468},
    ],
    'Chetan Agarwal (133_M3)': [
        {'name': 'Child Education', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2043-01-01', 'amount': 6147000.0, 'inflation_percent': 6.0},
    ],
    'Christopher Maram Reddy (135_M3)': [
        {'name': 'Travel Fund', 'type': 'Semi-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2027-01-01', 'amount': 700000.0, 'inflation_percent': 6.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 23},
    ],
    'Gaurav Bilgi (114_M3)': [
        {'name': "Daughter's Education UG", 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2030-03-01', 'amount': 625000.0, 'inflation_percent': 8.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 4},
        {'name': "Daughter's Education PG", 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2034-03-01', 'amount': 1250000.0, 'inflation_percent': 8.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 2},
        {'name': "Son's Education UG", 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2036-03-01', 'amount': 625000.0, 'inflation_percent': 8.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 4},
        {'name': "Daughter's Marriage", 'type': 'Semi-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2039-01-01', 'amount': 2500000.0, 'inflation_percent': 6.0},
        {'name': "Son's Education PG", 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2040-03-01', 'amount': 625000.0, 'inflation_percent': 8.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 4},
        {'name': "Son's Marriage", 'type': 'Semi-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2045-01-01', 'amount': 2500000.0, 'inflation_percent': 6.0},
        {'name': 'Travel', 'type': 'Semi-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2030-01-01', 'amount': 500000.0, 'inflation_percent': 8.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 7},
    ],
    'Kamleshkumar Chandrakant Joshi & Family (108_M3)': [
        {'name': "Daughter's Wedding", 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2028-01-01', 'amount': 2500000.0, 'inflation_percent': 6.0},
    ],
    'Karthik Ananthamurthy (150_M3)': [
        {'name': 'Child 1 UG', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2037-01-01', 'amount': 1666666.0, 'inflation_percent': 10.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 3},
        {'name': 'Child 1 PG', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2040-01-01', 'amount': 2500000.0, 'inflation_percent': 10.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 2},
        {'name': 'Child 2 UG', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2042-01-01', 'amount': 1666666.0, 'inflation_percent': 10.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 3},
        {'name': 'Child 2 PG', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2046-01-01', 'amount': 2500000.0, 'inflation_percent': 10.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 2},
        {'name': 'Vehicle Purchase', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2030-01-01', 'amount': 1000000.0, 'inflation_percent': 6.0},
    ],
    'Navin & Pushpa Jhanji (105_M3)': [
        {'name': 'DJ1 Marriage', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2028-01-01', 'amount': 6000000.0, 'inflation_percent': 6.0},
        {'name': 'DJ2 Marriage', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2029-01-01', 'amount': 7000000.0, 'inflation_percent': 6.0},
        {'name': 'SWP', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2028-01-01', 'amount': 70000.0, 'inflation_percent': 7.000000000000001, 'frequency': 'Monthly', 'end_mode': 'Occurrences', 'occurrences': 420},
    ],
    'Pradeep Chakravarthi Sadasivuni & Family (109_M3)': [
        {'name': 'Child 1 undergrad education', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2033-06-01', 'amount': 630000.0, 'inflation_percent': 10.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 4},
        {'name': 'Child 2 undergrad education', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2036-06-01', 'amount': 780000.0, 'inflation_percent': 10.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 4},
        {'name': 'Retirement income', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2048-01-01', 'amount': 261000.0, 'inflation_percent': 6.0, 'frequency': 'Monthly', 'end_mode': 'Occurrences', 'occurrences': 360},
    ],
    'Prakash Khanduja (138_M3)': [
        {'name': 'Child 1 undergrad education', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2035-01-01', 'amount': 2000000.0, 'inflation_percent': 6.0},
        {'name': 'Child 2 undergrad education', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2041-01-01', 'amount': 2000000.0, 'inflation_percent': 6.0},
        {'name': 'Retirement Income', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2047-01-01', 'amount': 200000.0, 'inflation_percent': 6.0, 'frequency': 'Monthly', 'end_mode': 'Occurrences', 'occurrences': 336},
    ],
    'Prateek Taneja (118_M3)': [
        {'name': 'Personal Wedding', 'type': 'Semi-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2026-12-01', 'amount': 1000000.0, 'inflation_percent': 6.0},
    ],
    'Ramesh Kurhade / Ranjana Kurhade / Ruthwick Kurhade / Rushikesh Kurhade (125_M3)': [
        {'name': 'Home Purchase', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2027-01-01', 'amount': 5000000.0, 'inflation_percent': 6.0},
    ],
    'Ranjeet Joshi (116_M3)': [
        {'name': 'Post-retirement incoming planning', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2027-05-01', 'amount': 190000.0, 'inflation_percent': 6.0, 'frequency': 'Monthly', 'end_mode': 'Occurrences', 'occurrences': 456},
    ],
    'Rohan Shyam Amladi (153_M3)': [
        {'name': 'Child UG', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2044-01-01', 'amount': 1333000.0, 'inflation_percent': 8.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 3},
        {'name': 'Child PG', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2048-01-01', 'amount': 1250000.0, 'inflation_percent': 8.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 3},
        {'name': "Child's Wedding", 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2053-01-01', 'amount': 1500000.0, 'inflation_percent': 6.0},
        {'name': 'Retirement Income', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2035-01-01', 'amount': 100000.0, 'inflation_percent': 6.0, 'frequency': 'Monthly', 'end_mode': 'Occurrences', 'occurrences': 492},
    ],
    'Sachin Sureka (119_M3)': [
        {'name': 'Marriage', 'type': 'Semi-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2036-01-01', 'amount': 2500000.0, 'inflation_percent': 6.0},
        {'name': 'Retirement Income', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2057-01-01', 'amount': 120000.0, 'inflation_percent': 6.0, 'frequency': 'Monthly', 'end_mode': 'Occurrences', 'occurrences': 132},
    ],
    'Sandeep B (139_M3)': [
        {'name': 'Child Ug', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2036-01-01', 'amount': 2000000.0, 'inflation_percent': 6.0},
        {'name': 'Child PG', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2040-01-01', 'amount': 1600000.0, 'inflation_percent': 6.0},
        {'name': 'Child Marriage', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2028-01-01', 'amount': 2000000.0, 'inflation_percent': 6.0},
        {'name': 'Vacation', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2028-01-01', 'amount': 2000000.0, 'inflation_percent': 6.0},
    ],
    'Santosh Praharaj (106_M3)': [
        {'name': 'Retirement Income', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2027-01-01', 'amount': 100000.0, 'inflation_percent': 6.0, 'frequency': 'Monthly', 'end_mode': 'Occurrences', 'occurrences': 384},
        {'name': 'Marriage', 'type': 'Semi-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2029-01-01', 'amount': 2500000.0, 'inflation_percent': 6.0},
        {'name': 'Marriage', 'type': 'Semi-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2032-01-01', 'amount': 2500000.0, 'inflation_percent': 6.0},
    ],
    'Soumitra & Sarmila Chakraborty (130_M3)': [
        {'name': 'Retirement Income', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2026-06-01', 'amount': 40000.0, 'inflation_percent': 6.0, 'frequency': 'Monthly', 'end_mode': 'Occurrences', 'occurrences': 12},
    ],
    'Sukumar Misra (141_M3)': [
        {'name': 'Vehicle Purchase', 'type': 'Semi-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2027-06-01', 'amount': 500000.0, 'inflation_percent': 6.0},
        {'name': 'Home Purchase', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2031-01-01', 'amount': 12500000.0, 'inflation_percent': 6.0},
    ],
    'Sunil Nagaraja Rao Mahendrakar (146_M1)': [
        {'name': 'Child UG', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2033-01-01', 'amount': 1500000.0, 'inflation_percent': 6.0},
        {'name': 'Child PG', 'type': 'Semi-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Lumpsum', 'start_date_mode': 'Fixed', 'start_date': '2037-01-01', 'amount': 2000000.0, 'inflation_percent': 6.0},
        {'name': 'Retirement Income', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2050-01-01', 'amount': 120000.0, 'inflation_percent': 6.0, 'frequency': 'Monthly', 'end_mode': 'Occurrences', 'occurrences': 276},
    ],
    'Sunil Shrikant Apte (136_M3)': [
        {'name': 'Financial Freedom', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2028-01-01', 'amount': 45000.0, 'inflation_percent': 6.0, 'frequency': 'Monthly', 'end_mode': 'Occurrences', 'occurrences': 366},
    ],
    'Vijay & Prachi Shepunde (101_M3)': [
        {'name': 'Son 1 Education', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2028-05-01', 'amount': 500000.0, 'inflation_percent': 7.000000000000001, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 3},
        {'name': 'Son 2 Education', 'type': 'Non-Negotiable', 'nature': 'Non-replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2032-05-01', 'amount': 500000.0, 'inflation_percent': 7.000000000000001, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 4},
    ],
    'Vijayaraghavan Panchanathan (151_M3)': [
        {'name': 'Child UG Education', 'type': 'Non-Negotiable', 'nature': 'Replenishing', 'structure': 'Recurring', 'start_date_mode': 'Fixed', 'start_date': '2030-01-01', 'amount': 500000.0, 'inflation_percent': 8.0, 'frequency': 'Annual', 'end_mode': 'Occurrences', 'occurrences': 4},
    ],
}


# ---------------------------------------------------------------------------
# Synthesized Personal & Corpus / Investment Stream profiles (D-P207-5).
# The tracker carries goals only; corpus and streams are deterministic
# functions of each client's total goal PV so configs are reproducible and
# scale sensibly with goal magnitude. (corpus_multiple, salary_multiple) --
# salary_multiple scales total_goal_pv/360 into a monthly salary.
# ---------------------------------------------------------------------------

PROFILES = {
    "lean": (0.10, 1.0),
    "moderate": (0.30, 2.0),
    "wealthy": (1.00, 4.0),
}


def total_goal_pv(goals):
    """Sum of PV amounts (per-occurrence amounts multiplied out for Recurring)."""
    total = 0.0
    for g in goals:
        n = g.get("occurrences", 1) if g["structure"] == "Recurring" else 1
        total += g["amount"] * max(1, int(n or 1))
    return total


def _engine_goal(g):
    out = dict(g)
    out["start_date"] = pd.Timestamp(g["start_date"])
    if "end_date" in g:
        out["end_date"] = pd.Timestamp(g["end_date"])
    return out


def build_config(client_key, profile="moderate"):
    """Engine config for one tracker client under a synthesized profile."""
    goals = [_engine_goal(g) for g in ADVISORY_CLIENTS[client_key]]
    corpus_mult, salary_mult = PROFILES[profile]
    pv = total_goal_pv(goals)
    return {
        "current_date": TODAY,
        "current_age": 45,
        "target_lifetime": 90,
        "current_corpus": round(corpus_mult * pv, 2),
        "investment_streams": [{
            "name": "Salary",
            "amount": round(salary_mult * pv / 360.0, 2),
            "start_date": TODAY,
            "end_date_mode": "At retirement",
            "end_date": None,
            "step_up_percent": 8.0,
            "step_up_frequency": "Annual",
            "step_up_date": TODAY - pd.Timedelta(days=1),
        }],
        "goals": goals,
        "one_time_investments": [],
    }
